monetary_data_extraction = '''
### Instructions:
Find the following Monetary Measures in this annual report file.
If the data cannot be found or calculated from the numbers provided in the report, return None.
If can return the number and all needed data in field value.
In “currency” specify only currency - EUR, USD etc.
In "references" show the physical page number in the PDF file (count number of page from first as 0 and to the end of the pdf file)

### Output schema:
JSON file:
{
  "monetary_measures": [
    {
      "name": "cash_flow_from_operations",
      "description": "The cash generated (or used) by the company’s core operating activities during the reporting period, expressed in a specified currency (e.g., USD, GBP).",
"currency": str,
   "value": float,
   "references": int    },
    {
      "name": "largest_single_executive_compensation",
      "description": "The highest single expenditure on executive compensation during the reporting period, expressed in the specified currency (e.g., USD, AUD).",
"currency": str,
   "value": float,
   "references": int    },
    {
      "name": "dividend_per_share",
      "description": "The dividend amount paid per share during the reporting period, expressed in the specified currency.",
"currency": str,
   "value": float,
   "references": int    },
    {
      "name": "capital_expenditures",
      "description": "The total monetary amount spent on capital investments during the reporting period, expressed in the specified currency (e.g., USD, EUR).",
"currency": str,
   "value": float,
   "references": int    },
    {
      "name": "rnd_spending_advanced_programs",
      "description": "The amount spent on advanced research and development programs during the reporting period, expressed in the specified currency.",
"currency": str,
   "value": float,
   "references": int    },
    {
      "name": "total_revenue",
      "description": "The aggregate revenue generated by the company during the reporting period, expressed in the specified currency.",
"currency": str,
   "value": float,
   "references": int    },
    {
      "name": "total_expensed_rnd_expenditure",
      "description": "The total research and development expenditure that was expensed during the reporting period, expressed in the specified currency.",
"currency": str,
      "value": float,
   "references": int

    },
    {
      "name": "total_deposits",
      "description": "The total amount of deposits held by the company at year-end, expressed in the specified currency.",
"currency": str,
      "value": float,
   "references": int
  }

]
}

'''