monetary_measures = [
    {
      "name": "cash_flow_from_operations",
      "description": "The cash generated (or used) by the company’s core operating activities during the reporting period, expressed in a specified currency (e.g., USD, GBP).",
      "value": 0
    },
    {
      "name": "largest_single_executive_compensation",
      "description": "The highest single expenditure on executive compensation during the reporting period, expressed in the specified currency (e.g., USD, AUD).",
      "value": 0
    },
    {
      "name": "dividend_per_share",
      "description": "The dividend amount paid per share during the reporting period, expressed in the specified currency.",
      "value": 0
    },
    {
      "name": "capital_expenditures",
      "description": "The total monetary amount spent on capital investments during the reporting period, expressed in the specified currency (e.g., USD, EUR).",
      "value": 0
    },
    {
      "name": "rnd_spending_advanced_programs",
      "description": "The amount spent on advanced research and development programs during the reporting period, expressed in the specified currency.",
      "value": 0
    },
    {
      "name": "total_revenue",
      "description": "The aggregate revenue generated by the company during the reporting period, expressed in the specified currency.",
      "value": 0
    },
    {
      "name": "total_expensed_rnd_expenditure",
      "description": "The total research and development expenditure that was expensed during the reporting period, expressed in the specified currency.",
      "value": 0
    },
    {
      "name": "total_deposits",
      "description": "The total amount of deposits held by the company at year-end, expressed in the specified currency.",
      "value": 0
    }
]
