message1 = '''
Analyze all the questions and make a list of the data in English that is missing from subset.json to answer all the questions.
'''
message2 = '''
Prepare a detailed descriptive for each metric by analyzing the list of questions.
'''

message3 = '''
Make a JSON scema that contains all Numerical Financial and Operational Metrics  as field names. And detailed data in nested dictionaries if needed. 
Example: 
{
"cloud_storage_capacity": {"value": int, "description": "The total amount of cloud-based data storage available to the company at the end of the reporting period, measured in terabytes"},
"employees_total_layoffs": {"value": int, "description": "A numerical value representing the total count of employees that were let go or terminated during the period covered by the annual report"}, 
"cash_flow_from_operations_values": {"value": int, "description": "A numerical value (reported in a specified currency USD, GBP, etc.) that indicates the cash generated (or used) by the company’s core operating activities during the reporting period"},  
"capital expenditures": {"value": int, "description": "The total monetary amount spent on capital investments during the reporting period. In specific currencies (USD, EUR, etc.) and indicates how much the company invested in fixed assets and infrastructure."},  
"active_software_licenses": {"value": int, "description": "A numerical value showing the count of active licensing agreements the company has at year-end."},  
"total_revenue": {"value": int, "description": "The aggregate revenue generated by the company during the reporting period. In specific currencies (USD, EUR, etc.)"},  
}
'''
message3 = '''
Collect in one list all numerical measures in money
'''